;
; Copyright (c) 2020 Anthony Beaucamp.
;
; This software is provided 'as-is', without any express or implied warranty.
; In no event will the authors be held liable for any damages arising from
; the use of this software.
;
; Permission is granted to anyone to use this software for any purpose,
; including commercial applications, and to alter it and redistribute it
; freely, subject to the following restrictions:
;
;   1. The origin of this software must not be misrepresented; you must not
;   claim that you wrote the original software. If you use this software in a
;   product, an acknowledgment in the product documentation would be
;   appreciated but is not required.
;
;   2. Altered source versions must be plainly marked as such, and must not
;   be misrepresented as being the original software.
;
;   3. This notice may not be removed or altered from any distribution.
;
;   4. The names of this software and/or it's copyright holders may not be
;   used to endorse or promote products derived from this software without
;   specific prior written permission.
;
; Serial static drivers: generated by co65 v 2.18 - N/A using model 'cc65-module'
;

	.fopt		compiler,"co65 v 2.18 - N/A"
	.case		on
	.debuginfo	off
	.export		_serial

;
; CODE SEGMENT
;
.segment	"CODE"
_serial:
	.byte	$73
	.byte	$65
	.byte	$72
	.byte	$02
	.byte	$00
	.byte	$00
	.word	_serial+24
	.word	_serial+24
	.word	_serial+41
	.word	_serial+24
	.word	_serial+186
	.word	_serial+252
	.word	_serial+299
	.word	_serial+311
	.word	_serial+333
	.byte	$AE
	.word	BSS+520
	.byte	$F0
	.byte	$05
	.byte	$A9
	.byte	$0A
	.byte	$9D
	.byte	$8A
	.byte	$C0
	.byte	$A9
	.byte	$00
	.byte	$AA
	.byte	$8E
	.word	BSS+520
	.byte	$60
	.byte	$A2
	.byte	$00
	.byte	$86
	.byte	<(ZEROPAGE+10)
	.byte	$A9
	.byte	$C0
	.byte	$0D
	.word	DATA+0
	.byte	$85
	.byte	<(ZEROPAGE+11)
	.byte	$BC
	.word	_serial+459
	.byte	$BD
	.word	_serial+463
	.byte	$D1
	.byte	<(ZEROPAGE+10)
	.byte	$D0
	.byte	$6D
	.byte	$E8
	.byte	$E0
	.byte	$04
	.byte	$90
	.byte	$F1
	.byte	$AD
	.word	DATA+0
	.byte	$0A
	.byte	$0A
	.byte	$0A
	.byte	$0A
	.byte	$AA
	.byte	$A0
	.byte	$04
	.byte	$B1
	.byte	<(ZEROPAGE+8)
	.byte	$C9
	.byte	$01
	.byte	$D0
	.byte	$5D
	.byte	$A0
	.byte	$00
	.byte	$8C
	.word	BSS+6
	.byte	$8C
	.word	BSS+0
	.byte	$8C
	.word	BSS+1
	.byte	$8C
	.word	BSS+3
	.byte	$8C
	.word	BSS+4
	.byte	$88
	.byte	$8C
	.word	BSS+2
	.byte	$8C
	.word	BSS+5
	.byte	$A0
	.byte	$00
	.byte	$B1
	.byte	<(ZEROPAGE+8)
	.byte	$A8
	.byte	$B9
	.word	_serial+428
	.byte	$30
	.byte	$40
	.byte	$85
	.byte	<(ZEROPAGE+16)
	.byte	$A0
	.byte	$01
	.byte	$B1
	.byte	<(ZEROPAGE+8)
	.byte	$A8
	.byte	$B9
	.word	_serial+448
	.byte	$05
	.byte	<(ZEROPAGE+16)
	.byte	$85
	.byte	<(ZEROPAGE+16)
	.byte	$A0
	.byte	$02
	.byte	$B1
	.byte	<(ZEROPAGE+8)
	.byte	$A8
	.byte	$B9
	.word	_serial+452
	.byte	$05
	.byte	<(ZEROPAGE+16)
	.byte	$09
	.byte	$10
	.byte	$9D
	.byte	$8B
	.byte	$C0
	.byte	$A0
	.byte	$03
	.byte	$B1
	.byte	<(ZEROPAGE+8)
	.byte	$A8
	.byte	$B9
	.word	_serial+454
	.byte	$09
	.byte	$01
	.byte	$8D
	.word	BSS+7
	.byte	$09
	.byte	$08
	.byte	$9D
	.byte	$8A
	.byte	$C0
	.byte	$8E
	.word	BSS+520
	.byte	$A9
	.byte	$00
	.byte	$AA
	.byte	$60
	.byte	$A9
	.byte	$04
	.byte	$A2
	.byte	$00
	.byte	$60
	.byte	$A9
	.byte	$08
	.byte	$A2
	.byte	$00
	.byte	$60
	.byte	$A9
	.byte	$05
	.byte	$A2
	.byte	$00
	.byte	$60
	.byte	$AE
	.word	BSS+520
	.byte	$AC
	.word	BSS+5
	.byte	$C8
	.byte	$F0
	.byte	$05
	.byte	$A9
	.byte	$00
	.byte	$20
	.word	_serial+384
	.byte	$AD
	.word	BSS+2
	.byte	$C9
	.byte	$FF
	.byte	$D0
	.byte	$05
	.byte	$A9
	.byte	$06
	.byte	$A2
	.byte	$00
	.byte	$60
	.byte	$AC
	.word	BSS+6
	.byte	$F0
	.byte	$11
	.byte	$C9
	.byte	$3F
	.byte	$90
	.byte	$0D
	.byte	$A9
	.byte	$00
	.byte	$8D
	.word	BSS+6
	.byte	$AD
	.word	BSS+7
	.byte	$09
	.byte	$08
	.byte	$9D
	.byte	$8A
	.byte	$C0
	.byte	$AC
	.word	BSS+0
	.byte	$B9
	.word	BSS+8
	.byte	$EE
	.word	BSS+0
	.byte	$EE
	.word	BSS+2
	.byte	$A2
	.byte	$00
	.byte	$81
	.byte	<(ZEROPAGE+8)
	.byte	$8A
	.byte	$60
	.byte	$AE
	.word	BSS+520
	.byte	$AC
	.word	BSS+5
	.byte	$C8
	.byte	$F0
	.byte	$07
	.byte	$48
	.byte	$A9
	.byte	$00
	.byte	$20
	.word	_serial+384
	.byte	$68
	.byte	$AC
	.word	BSS+5
	.byte	$D0
	.byte	$05
	.byte	$A9
	.byte	$07
	.byte	$A2
	.byte	$00
	.byte	$60
	.byte	$AC
	.word	BSS+4
	.byte	$99
	.word	BSS+264
	.byte	$EE
	.word	BSS+4
	.byte	$CE
	.word	BSS+5
	.byte	$A9
	.byte	$FF
	.byte	$20
	.word	_serial+384
	.byte	$A9
	.byte	$00
	.byte	$AA
	.byte	$60
	.byte	$AE
	.word	BSS+520
	.byte	$BD
	.byte	$89
	.byte	$C0
	.byte	$A2
	.byte	$00
	.byte	$81
	.byte	<(ZEROPAGE+8)
	.byte	$8A
	.byte	$60
	.byte	$05
	.byte	<(ZEROPAGE+9)
	.byte	$D0
	.byte	$0D
	.byte	$A6
	.byte	<(ZEROPAGE+8)
	.byte	$F0
	.byte	$09
	.byte	$E0
	.byte	$08
	.byte	$B0
	.byte	$05
	.byte	$8E
	.word	DATA+0
	.byte	$AA
	.byte	$60
	.byte	$A9
	.byte	$09
	.byte	$A2
	.byte	$00
	.byte	$60
	.byte	$AE
	.word	BSS+520
	.byte	$F0
	.byte	$2D
	.byte	$BD
	.byte	$89
	.byte	$C0
	.byte	$29
	.byte	$08
	.byte	$F0
	.byte	$26
	.byte	$BD
	.byte	$88
	.byte	$C0
	.byte	$AC
	.word	BSS+2
	.byte	$F0
	.byte	$14
	.byte	$AC
	.word	BSS+1
	.byte	$99
	.word	BSS+8
	.byte	$EE
	.word	BSS+1
	.byte	$CE
	.word	BSS+2
	.byte	$AC
	.word	BSS+2
	.byte	$C0
	.byte	$21
	.byte	$90
	.byte	$01
	.byte	$60
	.byte	$AD
	.word	BSS+7
	.byte	$9D
	.byte	$8A
	.byte	$C0
	.byte	$8D
	.word	BSS+6
	.byte	$38
	.byte	$60
	.byte	$85
	.byte	<(ZEROPAGE+16)
	.byte	$AD
	.word	BSS+5
	.byte	$C9
	.byte	$FF
	.byte	$F0
	.byte	$10
	.byte	$AD
	.word	BSS+6
	.byte	$D0
	.byte	$0B
	.byte	$BD
	.byte	$89
	.byte	$C0
	.byte	$29
	.byte	$10
	.byte	$D0
	.byte	$05
	.byte	$24
	.byte	<(ZEROPAGE+16)
	.byte	$30
	.byte	$E9
	.byte	$60
	.byte	$AC
	.word	BSS+3
	.byte	$B9
	.word	BSS+264
	.byte	$9D
	.byte	$88
	.byte	$C0
	.byte	$EE
	.word	BSS+3
	.byte	$EE
	.word	BSS+5
	.byte	$4C
	.word	_serial+386
	.byte	$FF
	.byte	$01
	.byte	$02
	.byte	$03
	.byte	$04
	.byte	$05
	.byte	$06
	.byte	$07
	.byte	$08
	.byte	$09
	.byte	$0A
	.byte	$0B
	.byte	$0C
	.byte	$0D
	.byte	$0E
	.byte	$0F
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$60
	.byte	$40
	.byte	$20
	.byte	$00
	.byte	$00
	.byte	$80
	.byte	$00
	.byte	$20
	.byte	$60
	.byte	$A0
	.byte	$E0
	.byte	$05
	.byte	$07
	.byte	$0B
	.byte	$0C
	.byte	$38
	.byte	$18
	.byte	$01
	.byte	$31

;
; DATA SEGMENT
;
.segment	"DATA"
DATA:
	.byte	$02

;
; BSS SEGMENT
;
.segment	"BSS"
BSS:
	.res	521

;
; ZEROPAGE SEGMENT
;
.import	__ZP_START__		; Linker generated symbol
ZEROPAGE = __ZP_START__

.end
