I2
.S'entries'
p0
.S'slicks'
p0
.S'64'
p0
.S'7'
p0
.S'5'
p0
.S'18'
p0
.S'8'
p0
.S'10'
p0
.S'18'
p0
.S'12'
p0
.S'21'
p0
.S'18'
p0
.S'7'
p0
.S'9'
p0
.S'17'
p0
.S'12'
p0
.S'6'
p0
.S'0.2'
p0
.S'$0C00'
p0
.S'$0100'
p0
.S'0,4,5,10,19'
p0
.S'listboxes'
p0
.(lp0
Vprojects/slicks/src/slicks.c
p1
aVprojects/slicks/src/game.c
p2
aVprojects/slicks/src/interface.c
p3
aVprojects/slicks/src/navigation.c
p4
aVprojects/slicks/src/network.c
p5
a.(lp0
Vprojects/slicks/bitmaps/menu-apple.png
p1
aVprojects/slicks/bitmaps/arizona-apple.png
p2
aVprojects/slicks/bitmaps/arto-apple.png
p3
aVprojects/slicks/bitmaps/cramp-apple.png
p4
aVprojects/slicks/bitmaps/freeway-apple.png
p5
aVprojects/slicks/bitmaps/gta-apple.png
p6
aVprojects/slicks/bitmaps/island-apple.png
p7
aVprojects/slicks/bitmaps/mtcarlo-apple.png
p8
aVprojects/slicks/bitmaps/rally-apple.png
p9
aVprojects/slicks/bitmaps/river-apple.png
p10
aVprojects/slicks/bitmaps/stadium-apple.png
p11
aVprojects/slicks/bitmaps/suzuka-apple.png
p12
a.(lp0
Vprojects/slicks/sprites/sprites-apple.png
p1
a.(lp0
Vprojects/slicks/music/speednik-apple.m
p1
a.(lp0
Vprojects/slicks/bitmaps/menu-atari.png
p1
aVprojects/slicks/bitmaps/arizona-atari.png
p2
aVprojects/slicks/bitmaps/arto-atari.png
p3
aVprojects/slicks/bitmaps/cramp-atari.png
p4
aVprojects/slicks/bitmaps/freeway-atari.png
p5
aVprojects/slicks/bitmaps/gta-atari.png
p6
aVprojects/slicks/bitmaps/island-atari.png
p7
aVprojects/slicks/bitmaps/mtcarlo-atari.png
p8
aVprojects/slicks/bitmaps/rally-atari.png
p9
aVprojects/slicks/bitmaps/river-atari.png
p10
aVprojects/slicks/bitmaps/stadium-atari.png
p11
aVprojects/slicks/bitmaps/suzuka-atari.png
p12
a.(lp0
Vprojects/slicks/sprites/sprites-atari.png
p1
a.(lp0
Vprojects/slicks/music/speednik-atari.rmt
p1
a.(lp0
Vprojects/slicks/bitmaps/menu-c64.png
p1
aVprojects/slicks/bitmaps/arizona-c64.png
p2
aVprojects/slicks/bitmaps/arto-c64.png
p3
aVprojects/slicks/bitmaps/cramp-c64.png
p4
aVprojects/slicks/bitmaps/freeway-c64.png
p5
aVprojects/slicks/bitmaps/gta-c64.png
p6
aVprojects/slicks/bitmaps/island-c64.png
p7
aVprojects/slicks/bitmaps/mtcarlo-c64.png
p8
aVprojects/slicks/bitmaps/rally-c64.png
p9
aVprojects/slicks/bitmaps/river-c64.png
p10
aVprojects/slicks/bitmaps/stadium-c64.png
p11
aVprojects/slicks/bitmaps/suzuka-c64.png
p12
a.(lp0
Vprojects/slicks/sprites/sprites-c64.png
p1
a.(lp0
Vprojects/slicks/music/speednik-c64.sid
p1
a.(lp0
Vprojects/slicks/bitmaps/menu-oric.png
p1
aVprojects/slicks/bitmaps/arizona-oric.png
p2
aVprojects/slicks/bitmaps/arto-oric.png
p3
aVprojects/slicks/bitmaps/cramp-oric.png
p4
aVprojects/slicks/bitmaps/freeway-oric.png
p5
aVprojects/slicks/bitmaps/gta-oric.png
p6
aVprojects/slicks/bitmaps/island-oric.png
p7
aVprojects/slicks/bitmaps/mtcarlo-oric.png
p8
aVprojects/slicks/bitmaps/rally-oric.png
p9
aVprojects/slicks/bitmaps/river-oric.png
p10
aVprojects/slicks/bitmaps/stadium-oric.png
p11
aVprojects/slicks/bitmaps/suzuka-oric.png
p12
a.(lp0
Vprojects/slicks/sprites/sprites-oric.png
p1
a.(lp0
Vprojects/slicks/music/speednik-oric.ym
p1
a.(lp0
Vprojects/slicks/navigation/arizona.nav
p1
aVprojects/slicks/navigation/arto.nav
p2
aVprojects/slicks/navigation/cramp.nav
p3
aVprojects/slicks/navigation/freeway.nav
p4
aVprojects/slicks/navigation/gta.nav
p5
aVprojects/slicks/navigation/island.nav
p6
aVprojects/slicks/navigation/mtcarlo.nav
p7
aVprojects/slicks/navigation/rally.nav
p8
aVprojects/slicks/navigation/river.nav
p9
aVprojects/slicks/navigation/stadium.nav
p10
aVprojects/slicks/navigation/suzuka.nav
p11
a.(lp0
Vprojects/slicks/bitmaps/banner-lynx.png
p1
aVprojects/slicks/bitmaps/menu-lynx.png
p2
aVprojects/slicks/bitmaps/arizona-lynx.png
p3
aVprojects/slicks/bitmaps/arto-lynx.png
p4
aVprojects/slicks/bitmaps/cramp-lynx.png
p5
aVprojects/slicks/bitmaps/freeway-lynx.png
p6
aVprojects/slicks/bitmaps/gta-lynx.png
p7
aVprojects/slicks/bitmaps/island-lynx.png
p8
aVprojects/slicks/bitmaps/mtcarlo-lynx.png
p9
aVprojects/slicks/bitmaps/rally-lynx.png
p10
aVprojects/slicks/bitmaps/river-lynx.png
p11
aVprojects/slicks/bitmaps/stadium-lynx.png
p12
aVprojects/slicks/bitmaps/suzuka-lynx.png
p13
a.(lp0
Vprojects/slicks/sprites/sprites-lynx.png
p1
a.(lp0
Vprojects/slicks/music/speednik-lynx.asm
p1
aVprojects/slicks/music/chase-lynx.asm
p2
aVprojects/slicks/music/driven-lynx.asm
p3
aVprojects/slicks/music/stroll-lynx.asm
p4
aVprojects/slicks/music/whirlwnd-lynx.asm
p5
a.(lp0
.(lp0
.(lp0
.(lp0
.(lp0
.(lp0
.(lp0
.(lp0
.(lp0
.(lp0
.(lp0
.S'checkbuttons'
p0
.(S'selected'
p0
tp1
.S'comboboxes'
p0
.S'360KB'
p0
.