/*
 *	API of the "8bit-Unity" SDK for CC65
 *	All functions are cross-platform for the Apple IIe, Atari XL/XE, and C64/C128
 *	
 *	Last modified: 2021/12/25
 *
 * Copyright (c) 2021 Anthony Beaucamp.
 *
 * This software is provided 'as-is', without any express or implied warranty.
 * In no event will the authors be held liable for any damages arising from
 * the use of this software.
 *
 * Permission is granted to anyone to use this software for any purpose,
 * including commercial applications, and to alter it and redistribute it
 * freely, subject to the following restrictions:
 *
 *   1. The origin of this software must not be misrepresented * you must not
 *   claim that you wrote the original software. If you use this software in a
 *   product, an acknowledgment in the product documentation would be
 *   appreciated but is not required.
 *
 *   2. Altered source versions must be plainly marked as such, and must not
 *   be misrepresented as being the original software.
 *
 *   3. This notice may not be removed or altered from any distribution.
 *
 *   4. The names of this software and/or it's copyright holders may not be
 *   used to endorse or promote products derived from this software without
 *   specific prior written permission.
 */

#include "../../unity.h"

#pragma rodata-name("CODE")
#pragma code-name("CODE")

extern unsigned char  fileNum;     	// Variable auto-generated by Build Script
extern unsigned int   fileSizes[];  //					"
extern unsigned char  fileBanks[];  //					"
extern unsigned char* fileNames[];  //					"
extern unsigned char* fileDatas[];  //					"

#pragma bss-name(push, "XRAM")

unsigned char fileIndex, fileBank, *fileData, fileName[13];
unsigned int fileSize, consummed = 0;

#pragma bss-name(pop)

void DirList(void)
{
	// Do nothing, file list is assembled at build time!
}

unsigned int FileOpen(const char* filename)
{
	for (fileIndex=0; fileIndex<fileNum; fileIndex++) {
		memcpyBanked(fileName, fileNames[fileIndex], 13, 1);
		if (!strcmp(filename, fileName)) {
			set_prg_bank(1);
			fileBank = fileBanks[fileIndex];
			fileData = fileDatas[fileIndex];
			fileSize = fileSizes[fileIndex];
			set_prg_bank(0);
			consummed = 0;
			return fileSize;
		}
	}
	return 0;
}

unsigned int FileRead(char* buffer, signed int len)
{
	// Check remaining size
	if (len == -1 || len > fileSize - consummed)
		len = fileSize - consummed;
	
	// Copy chunk of data while bank switching
	memcpyBanked(buffer, fileData+consummed, len, fileBank);
	
	// Update consummed data
	consummed += len;
	return len;	
}

void FileClose(void)
{
}
