# Oric-focused build harness for 8-bit Unity
# 
# Should build Oric .DSK binaries
#
name: build-8bit-unity-demos-for-oric

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: windows-2019
    steps:

    - name: Checkout 8bit Unity source files
      uses: actions/checkout@v2

    - name: Generate the builder .BAT file for Oric
      run: cd D:\a\8bit-Unity\8bit-Unity\; .\_builder_.bat -projectFile projects\demos\demo.builder -useGUI 0 -callEmu 0
 
    - name: Build 8bit Unity Demos for Oric (.DSK file)
      run: cd D:\a\8bit-Unity\8bit-Unity\build; .\demos-oric48k.bat

    - name: Upload Oric DSK file
      uses: actions/upload-artifact@v2
      with:
        name: demos-oric48k.dsk
        path: build/demos-oric48k.dsk

