# Oric-focused build harness for 8-bit Unity
# 
# Should build Oric .DSK binaries
#
name: unity-OS-for-oric

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: windows-2019
    steps:

    - name: Checkout 8bit Unity source files
      uses: actions/checkout@v2

    - name: Generate the builder .BAT file for Oric
      run: cd D:\a\8bit-Unity\8bit-Unity\; .\_builder_.bat -projectFile projects\os\os.builder -useGUI 0 -callEmu 0


    - name: Build 8bit Unity OS for Oric (.DSK file)
      run: cd D:\a\8bit-Unity\8bit-Unity\build; .\os-oric48k.bat

    - name: Upload Oric DSK file
      uses: actions/upload-artifact@v2
      with:
        name: os-oric48k.dsk
        path: build/os-oric48k.dsk

