# Oric-focused build harness for 8-bit Unity
# 
# Should build Oric .DSK binaries
#
name: build-8bit-unity-for-oric

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: windows-2019
    steps:

    - name: Checkout source files
      uses: actions/checkout@v2

    - name: Run build
      run: cd D:\a\8bit-Unity\8bit-Unity\build; .\os-oric48k.bat

    - name: Upload DSK files
      uses: actions/upload-artifact@v2
      with:
        name: upload DSK files
        path: build/*dsk

    - name: Find output
      run:  |
        find . -name "*.dsk" -ls
      
